// Intentionally empty.
//
// Data pack splitting is handled in `project_files/web/shell.html` by intercepting
// `fetch('hwengine.data')` and transparently streaming `hwengine.data.partN` files.
//
// Reason: the `.data` loader generated by Emscripten in this repo expects
// `Module.getPreloadedPackage()` to return an `ArrayBuffer` synchronously, not a
// Promise, so an async split-loader hook will break at runtime.
